data:
  env: config-eureka-dev
  user:
    username: eureka-client
    password: '{cipher}AQBjsxq9kGwvrSUL0zj8VES2mr6a9JsRgxzTGY95FOvhvchCftn75JXNRxqpLES/vEt04rIBfU7mBphwJhxGYxVvJbu/feOT/C7S3qY1Mg6JT2ikISgC3uKwugVL7kHNs7RZEB9zKCubEYnkw+XcWZ+S47+gTavOOR11zpeLwplTlDIGlLOiSA60GMchnJaOuBdbGvBLOkaIo8KOMrcSgpSqcBoxxkssetOZIwv+SpzSNea70JH1cZj52UzmwSZn6w+I5HY7wu+6MUHlc8xrQsIISc7ruQEfC9ilH17gWI6+LfJmM6ChHaF2atXrNXyWPfYSiNNWIDlabsiWbtDuuoDHH6tRewyWgrhQEPWqyquimMh3xjeNaGh0HBL8qo0Ef3o='
