data:
  env: config-eureka-dev
  user:
    username: eureka-client
    password: '{cipher}AQCCVq12LFpF8jO611UBqw6AVRBxP9Zacu3w047iTG+aMQaUMmCVPkeVRAy2dz/PbAWuh7vvb2XLEohzNdiS6TFIjvmhGmtkA2X94qmr4OKEW/cSEGjuhA9jDoZ2pNxy+6YMY4VYaPXVHs1YxbyREAI3xX5dD063byE9bGIYCS5qZvAZ3MVmdOpGSTkykVaNMJ1udIXCyirTnF7K0jEcVAbgodKcGmdklzoRmsLQqJ818UccDU3rNF9VUCXB3bcj7DcKqMrp7KakoCcv+qTCuUQkn/94y/YuVphFQ1hJ0XtIq51977RGjhZzGwzhDXDJegx+WAi6Q2NbZnM52VEjfvOpmWgc4sFkgeG/nkG1BKF8qZliJcAkg/kbIfBuVv9hua0='
