data:
  env: config-eureka-dev
  user:
    username: eureka-client
    password: '{cipher}AQA/vfjOtIW02Rc15uPX/H4w+Sb9lGLQRm7tgf8xGTx4+iq/M7M8ntJki2nwa1sII39+LiQ2LYXtsVRRLTJ0++1Rf/u89A9N9lg721zHjUhc8T/3Kahwg3Tsn2k7UPVmTkBlHPGV8J7ye3essfokfc+4ir/WrY4D+ss+uNzngvR3yBxgn5/BWV6h7kjG1d97Wav2IGrxtSDn3i2oeIQmsllmDoiaetEuxGDQvJCEhoMt/Mo2OlycWF4hDxLE1TR9P/UknKU8CIjHaOx2UL5SW2lhO33p/ObM26JCU+2LZeTrc2DJ1k8/8CPkim9PT2UjKUhndETtwRnS48y0C3knXiCiedTO6JF9mpwHe0WtZW5VmfjKl4f/0KFLROYVyGbA71Q='
