data:
  env: config-eureka-dev
  user:
    username: eureka-client
    password: '{cipher}AQA0QuAgTWG+13mX/JKBm69umSf1dKw3Qs/56hocdmjkeYX2XlO9QdGaVCrPBrwaiUzdWK6B+cR+/U48nhpzzHsSbdNhWsrUh5N6vKqdaIXdPYUDlNZKSdHwsc3fA0QamqF6MxIf75z6GVXElF6IpNE0A76Pzla94AitR2jFg/SXMsjq8oMzgXZaCxXPp21m7zJKZ0tR5NwpqmSG3bN5I5iwdNowEick8Quuo51iRkVXser+GBAsFPpDv+1HOLIDYGwgo43VQstJjYljY4xwxbsCyMwYx6ncMQWfzNVVq4fmrGMRWyIkszX560LW5zIgiuEKovCp01jWNf7UNF3qYf9gIqdxn1wGLi3kz9/If1F5VSjRKEQ9wZ/T1pSkRYxHX2E='
